### ISSUE TITLE
~HeavenMS~ Bugs List

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#139]
hello, im use the lastest of HeavenMS without Neo City XML.

i/l - skill very low Damage. 

**Hawkeye NPC Pirate:**
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: TypeError: Cannot find function getplayer in object scripting.quest.QuestActionManager@12377ff6. (#24) in at line number 24

Quest number: 20105
Its happend only to KOC Pirate.

KPQ: 
party is getting bugged when we was getting 3, as 2 in party no problems but whne i added 1 more. 1 of 3 dosent gett exp

Lilin NPC Aran: After put medal on me - quest just spam msg me [when you take thje medal off it doesnt spam]

Commands.java:
how can i remove case "whatdropsfrom": since i remove all lines

"whodrops" make a error with if(listIterator and output = ""; just error

quest id 2162 broken cant reward etc:
https://mapletip.com/maplestory-quest/The+Half-written+Letter/2162/

**Comment by ronancpl** [comment]
There is no guarantee things will behave properly if client WZ's and server WZ.xml's are not synchronized. If their "versions" doesn't match, things like that is bound to happen.
Like, if one doesn't update the client Wz and update the server Wz.xml, one of the collateral effects is the map having their NPCs all messed up, since the client recovers the NPC info from the server.

**Comment by Soyrce** [comment]
thank ronan, XML been fixed and npcs.

Question added:
how can i added Quest Exp RATE?
public static final boolean?

New Bugs list:
KOC [noblesse] sometimes glitch [after completed all quest tutorial] how can disable quest tutorial to job adv cygnus?

KPQ: 
party is getting bugged when we was getting 3, as 2 in party no problems but whne i added 1 more. 1 of 3 dosent gett exp

Rien NPC Aran: After reward medal - quest just spam msg me

**Comment by Soyrce** [comment]
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: TypeError: Cannot find function getplayer in object scripting.quest.QuestActionManager@12377ff6. (<Unknown source>#24) in <Unknown source> at line number 24

Quest number: 20105

**Comment by ronancpl** [comment]
Is that the only inconsistence with KoC job adv?

**Comment by ronancpl** [comment]
In KPQ, provided everyone is in the level range and entered the PQ normally, they all gain exp accodingly.

**Comment by ronancpl** [comment]
To figure out how to apply a Quest rate, try finding the code points where exp is given to the player (generally Quest Action section) and add a multiplier there.

**Comment by Soyrce** [comment]
Hello ronan, **i have edit my lastest post, please read again :)** look ups

About Quest rate point func i have no idea about it. :(
KPQ i have changed it to 21 ~ 50.

**Comment by Soyrce** [comment]
New Bug:
KOC Dawn Warrior 3rd JOB, Cant find 1104100/1101003 NPC In hidden map

NPC:  mihile

**Comment by ronancpl** [comment]
KoC 3rd job is basically defeat the master of disguise boss and retrieve the loot afterwards. From what I could grasp, this aspect is already working.

**Comment by Soyrce** [comment]
ronan, i'm not stupid.

I know you have to click the NPC and then the Boss appears but the problem is that there is nothing on the map they did by the All Guide and the Tasks for it.

Please read all bugs list i writed

**Comment by ronancpl** [comment]
That's not the matter. In the current version of the source, no NPC will appear to the player. Every 2nd class attempting the boss would need to go to "Training Forest I" and cross the portal to "Tiv's Forest", that's all.

scripts/portal/enterDisguise2.js : this script calls the boss to the player once they get in the boss map. No npcs to talk.

**Comment by Soyrce** [comment]
@ronancpl so can you fix this boss summon NPC: mihile
Quest number: 20105 ? and upload and please look into all bugs list.

i really tired to find all bugs, my server broken :-1:  :(

**Comment by ronancpl** [comment]
Well, bug troubleshooting is the daily management of anyone inclined to set up a server online, bluntly said. Since I assume you are wanting to set up an online server with this source, it is assured that you WILL find many bugs out there, some of them easy to solve, some not so easy. Yes, I get this is not beginner-friendly, but that's the way software enginneering goes.

I suggest you to start taking lessons of the basics of algorithms and data structures, basics on Java and, from that standpoint, start discovering what you can do to improve the source you are currently running. Scripting for those quests and NPCs are not so hard once you start understanding the concepts (that can be learned from working examples all throughout the source).

**Comment by Soyrce** [comment]
Hey, I know JAVASCRIPT, but JAVA does not and sometimes I get errors that I have no idea how to fix.

that why i ask you to check it urself.

**Comment by Soyrce** [comment]
can i have your Discord user or skype? to show you all bug list.

All SHOP NPC dc

**Comment by ronancpl** [comment]
All shop NPC d/c.
Portals leading to maps with bosses with HP bar added by myself (possibly the 3rd job thief map d/c issue probably).

These two crashes, and many more, occurs because a client is not loading the proper WZs (the ones on the Drive). Since those WZs doesn't have the new features added, they fail to sync with the server XMLs, that have the features bundles.

That's why I stated in a lot of places that players using the clean/different WZs would not behave properly when using this server source.
