### ISSUE TITLE
error maplecharacter lastest update

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#140]
i tried to edit the lastest update maplecharacter.java and show error:
```
error: method broadcastGMMessage in class Server cannot be applied to given types;
        Server.getInstance().broadcastGMMessage(this.getWorld(), MaplePacketCreator.serverNotice(6, MapleCharacter.makeMapleReadable(this.name) + " was autobanned for " + reason));
  required: byte[]
```

[bla.txt](https://github.com/ronancpl/HeavenMS/files/1562448/bla.txt)

**Comment by ronancpl** [comment]
Before the commit the signature for broadcastGMMessage was: (final byte[] packet);
Now it is (int world, final byte[] packet).

Since the last commit makes it need the "int world" parameter alongside the function call, to solve this you simply have to change your broadcastGMMessage to use the new signature or remove the this.getWorld() parameter from the call.

MaplePacketCreator.serverNotice returns a byte[] btw, the only parameter required in your case.

**Comment by Soyrce** [comment]
yeah, sorry mymistake forget to add server.java
