### ISSUE TITLE
Question to add something

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#141]
Hello Ronan, how can i add Notice or Achievements

[Achievements] Congrats %s has reach level 120.
[Notice] Soyrce has joined, enjoy..

i tried in MapleCharacter.java but won't work

**Comment by ronancpl** [comment]
You can make use of Server broadcastMessage(c.getWorld(), MaplePacketCreator.serverNotice(int mode, String message)); to send a string "message" (such as the Notice) to every player on the given world.

For achievements, try using MapleCharacter dropMessage(int mode, String message). You may want to build a proper class file to record achievements to the player.

**Comment by Soyrce** [comment]
'm pretty new at this I do not know how to set a function to something specific.

Say a new player joins and sees a message: How to set it up and where?

**Comment by ronancpl** [comment]
Check PlayerLoggedinHandler.

**Comment by Soyrce** [comment]
ok i will check it.

i had a prob with Maker [level 3 skill] im trying to cm.teachskill - from npc chef at lith harbor. but nothing happens how can i add Maker skill to all players ? Begginer Book

**Comment by ronancpl** [comment]
cm.teachSkill, when done properly, should give you the skill with no problems. If that's not the case, something is off there. Since there is 3 ids for Maker skill, I assume:
1007 -> for Explorers, 10001007 -> for Cygnus, 20001007 -> for Legend

To target all players, you must figure out a way to reach them. There are several ways to do it, but it needs proper delving into the subject. If you want to target them online, the solution is rather easy, just apply it to all online players. If you want to target offline ones as well, make a way to add this operation on the DB. Etc etc.

**Comment by Soyrce** [comment]
on constant.skill
i have only nobless.java = 10001007 | legend.java = 20001007 there is no begginer.

please help me to add to job book I or npc teachskill?

**Comment by Soyrce** [comment]
Erm 1 quest is broken  Memory Lane,  i speaked wiht Grendal the realy old,  but then quest diddent gett compleated

**Comment by ronancpl** [comment]
That quest should work provided you have set the provided Wz.
