### ISSUE TITLE
error logs

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#142]
what these it mean? could fix?
MustardS

**Comment by ronancpl** [comment]
net.server.channel.handlers.PlayerLoggedinHandler.txt: yet another issue with Wz's. On the rate coupon's nodes, I've added a "time" component along with other things to make the server display active coupons as a "buff" (top-right corner icon).

net.server.channel.handlers.GeneralChatHandler.txt: ArrayOutOfBounds occurred, there is an element lacking on the array given to the command. Btw, this stacktrace over there means nothing here, the code already differs from mine.

**Comment by Soyrce** [comment]
Hai what you mean display active coupons as a "buff" < You can specify more please, where to turn off?

Generalchathandler: Already differs from mine, and what about mine why his show error?

**Comment by ronancpl** [comment]
There is no "where to turn it off". It is up to you to devise a way to remove this Wz dependency throughout your source, since you don't want to have that feature. It involves to delve through your current code and work your way through it.

An Exception stacktrace is something highly specific to code. You cannot expect me to understand what is going on your side since the given problem is clearly somewhere else on the file, not on the exact lines as the stacktrace depicts.
