### ISSUE TITLE
BUGGED

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#150]
why i cant Item Smega this MapleHAT???
![image](https://user-images.githubusercontent.com/34108561/34454578-06efa746-ed77-11e7-9650-9e14445af4a5.png)

how can enable untradeable to show in smega?

**Comment by Soyrce** [comment]
<iframe src="https://discordapp.com/widget?id=379336076671713283&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>

**Comment by jaydenseah** [comment]
Hi Soyrce, I believed that this is not a "bug". Have you try using Scissor of Karma before smega it?

**Comment by Soyrce** [comment]
Yeah ik karma, but i see some server can use item smega on untradeable item.

**Comment by ronancpl** [comment]
This is not a bug. Item smega will refuse to display items that returns true when calling isDropRestricted(). See UseCashItemHandler line 349 for clearance.
Some untradeable items on inventory bypasses this check since their "original state" are those of a tradeable ones, but the right is that untradeable items couldn't even be displayed by the smega.
