### ISSUE TITLE
error unregisterbuff

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#151]
[    public void unregisterChairBuff() {
        if(!ServerConstants.USE_CHAIR_EXTRAHEAL) return;
        
        int skillId = getJobMapChair(job);
        int skillLv = getSkillLevel(skillId);
        if(skillLv > 0) {
            MapleStatEffect mapChairSkill = SkillFactory.getSkill(skillId).getEffect(skillLv);
            cancelEffect(mapChairSkill, false, -1);
        }
    }](url)

Line: 8069
unregisterChairBuff();

[accountStuck.txt](https://github.com/ronancpl/HeavenMS/files/1597966/accountStuck.txt)

**Comment by ronancpl** [comment]
SkillFactory.getSkill(skillId) returned a null when it should have returned something else. Check if you have the node ids 10000100 and 20000100 on your Skill.wz xml file.

If you don't have (you probably don't, since that is from a modified structure), I would suggest you to change the getJobMapChair() function to only return 100, since that one skill id is surely an existing one.
