### ISSUE TITLE
why my old thread closed?

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#159]
please dont close my last thread, Before the problem was resolved
https://github.com/ronancpl/HeavenMS/issues/158

  Had more bugs list:
cant use the thorn remover on the thorns to remove them for the mushking empire quests

For the aran questline, 
The quest "Green Mushrooms" required me to kill 25 Dejected Green Mushrooms and also obtain a Dejected Green Mushroom Puppet which drops from them, which I completed just fine. (Took maybe ~5-10minutes)

Now a couple quests down the line from that, "Rowen Request 1", requires me to kill 100 Green Mushrooms/Dejected Green Mushrooms and obtain another Dejected Green Mushroom Puppet, however this time didn't go so well. I killed the 100 but after almost an hour of hunting the puppet  STIlL HASN'T DROPPED.. what's up with that?! I'm convinced the drop for it is bugged thx

**Comment by ronancpl** [comment]
Firstly, sorry for the inconvenience, but the issues list on this repository should be used only to address problems occuring on this source, provided the testing environment is under the given constraints (same Wz, unmodified code-base). Please open a thread in development forums such as RageZone for hints and queries about problems in your end.

Found a solution for the MK Thorn Remover.

The "Rowen Request 1" quest is not bugged, the drop merely doesn't have an entry on the SQL tables... Check on drop_data for drop id 4032317. Note that there will have other quests with the item not being dropped, due to the lengthy nature of the Maple questlist, one must add them incrementally to the drop data.

**Comment by Soyrce** [comment]
I downloaded all of your WZ.

But how do you get along with them? What to put in the V83 folder, and what to give to players in RAR? And go up to the site? How do I know how to operate?

**Comment by ronancpl** [comment]
Everything related to setting a test environment should be depicted on the readme already.

Server-side: all XMLs inside the "wz" folder at the root of the project.
Client-side: overwrite all .wz files with the ones provided.

Regarding distributing wz for players on a site, that should be figured out elsewhere.

**Comment by ronancpl** [comment]
Applied relevant fixes regarding this issue. Closing this.
