### ISSUE TITLE
error portal

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#160]
....? just got this error 
[enterFirstDH.txt](https://github.com/ronancpl/HeavenMS/files/1621922/enterFirstDH.txt)

New Error (please do not close my thread until fix). 
[net.server.channel.handlers.AutoAggroHandler.txt](https://github.com/ronancpl/HeavenMS/files/1621931/net.server.channel.handlers.AutoAggroHandler.txt)
[net.server.channel.handlers.ItemRewardHandler.txt](https://github.com/ronancpl/HeavenMS/files/1621932/net.server.channel.handlers.ItemRewardHandler.txt)
[net.server.channel.handlers.MoveLifeHandler.txt](https://github.com/ronancpl/HeavenMS/files/1621933/net.server.channel.handlers.MoveLifeHandler.txt)

**Comment by ronancpl** [comment]
Some things you should know: 
Firstly, threads I deem not a problem here will be closed thoroughly. Anyway, I will give hints to the solution in those "not-a-problem" cases. Where I see use for solutions on this source, I will apply them.
Secondly, don't plainly use the "fix" word as if it is a magical solution for everything, it is not.

Now for the issues:
There is a high chance the MapleCharacter "map" attribute has been set to null before those handlers got called. Since they are not game crashing, that's fine.
ItemRewardHandler doesn't have a strack trace... If you can, try to reproduce that error to usderstand what is going on.

**Comment by Soyrce** [comment]
ok ronan <3, i really dont know what happened to pet loot.

the wingboots for pets do not work properly, the pet do not move towards the mesos/item
pet don't seem to pick up items when you're standin still, if you start movin they start picking up items
2 people of my server test it

**Comment by ronancpl** [comment]
That seems to be a client-side issue, past the scope of server-side development. As it seems, the localhost being used or something is not making the proper movement effect when the pet has the wing boots equipped. Basic testing here shows the item working out just fine.

**Comment by ronancpl** [comment]
Those issues suggests c.getPlayer() is null in edge case scenarios (a player is in process of logging off/disconnecting). No major problems there. Issues above has been dealt as well.
