### ISSUE TITLE
SQL drop_data minimum/maximum_quantity not working

### ISSUE THREAD

**Issue by JaFont** [ronancpl/HeavenMS#180]
For instance zakum, if i change the min on zhelms from 1->2 and max from 1->4 and leave chance as is and set the global droprate to 10000x i still only get 1 zhelm dropping.

**Comment by ronancpl** [comment]
Originally, equipments were not supposed to use the minimum/maximum_quantity fields at all, since these fields are used to fill in the quantity range of an item that is to be dropped by a monster as one map object.

I've figured out that feature could be nice to have around, so that has been added now. Thanks for the feedback.

Btw, equip minimum/maximum_quantity will work differently than other items. It will describe "extra" equipment drop chance. Suppose range 2~3 on equips: at a mobdrop event, a random between 2 or 3 equips of that itemid CAN be dropped, each one running it's own drop chance instance.
