### ISSUE TITLE
Aran Quest Issue lvl 63 quest

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#186]
Let me start by saying I appreciate all your hard work and help on the source you provide the public.

Now, When you hit level 63 Aran. The quest 21752 can be started and completed. Once you complete 21752, quest 21753 should be available in the quest tab. It doesn't show up at all and I'm unsure how to make it show up so I can start the quest. 

Thanks for your help!

**Comment by ronancpl** [comment]
The Lost Seal Stone of Ellin Forest (21753) should be available after you complete the quest 21751. Quest 21752 serves only as a sidequest to obtain the Storage Key item.

Another thing that should be noted, this snippet was on the original v83 Quest.wz, at the node of the questid 21753:
```
<int name="infoNumber" value="21764"/>
      <imgdir name="infoex">
        <imgdir name="0">
          <string name="value" value="1"/>
        </imgdir>
      </imgdir>
      ...
```

Since the infoNumber, infoEx data have been deprecated for the purposes of this server, the Quest.wz client file must be edited to remove that check on client-side, and allow to show available the next quest.

**Comment by iAlpex** [comment]
Also had to remove that node from the server side wz. Thanks. Thread closed
