### ISSUE TITLE
Mobs won't spawn

### ISSUE THREAD

**Issue by BangPower** [ronancpl/HeavenMS#210]
Hi there!
its really weird after certain time players stuck in game and wont be able to login the game freeze mobs won't spawn.

**Comment by iAlpex** [comment]
This issue has already been posted. There is still no known issue at this time.

**Comment by ronancpl** [comment]
It is known that this server is not stable by any means.

There are many issues that, on the big picture, would result on the world server eventually crashing. Only by solving several minor issues on a chewable way, that that situation can be lifted.

Said this, since this issue is too broad to approach for now, I'm closing it. Yet, I can give a hint on what is probably going on:

Due to the asynchronous nature of the clients' representation at the server-side on a typical client-server architecture, and the need of syncronization of that to make the server operations at least palpable, locks are substantial elements of the source code.

However, depending on the way locks are picked would lead to deadlocks, that would lead to all these symptoms you've reported (essentially server crashing). This would be the case here, unfortunately.

**Comment by BangPower** [comment]
if i want to pay you money or your coding skills its something we can do together?
my server is hosted on a VDS its important for me to let the server succeed can i pay you for several fixes?
