### ISSUE TITLE
Code services

### ISSUE THREAD

**Issue by BangPower** [ronancpl/HeavenMS#211]
Hi genius.
i have my own server and i really love it that's my only therapy i currently have.
i really like when people play and tbh i paid a lot of money for VDS and stuff,
there's any chance i pay you money to fix few simple things for me?

**Comment by ronancpl** [comment]
Some time later this issue, we had a private discussion about this. I am sorry about the inconveniences regarding this server source not being stable, although information disclaiming that were present since the beginning.

For other parties looking towards hiring me specifically for private Maple development, I am sorry but due to both legal and moral circumstances I am not looking towards this kind of offer.
