### ISSUE TITLE
dropspider not working.

### ISSUE THREAD

**Issue by vince538** [ronancpl/HeavenMS#219]
When you try to run dropspider to crawl for data on hidden-street.
It runs well and says finished crawling sections.
WZ files are in default directory checked Main.java for the dropspider config.

Now the problem is when it's finished, it generated the 2 files error.txt & drops.sql
But the drops.sql is kinda empty without the actual data it does give you the sql arguments:

TRUNCATE TABLE `drop_data`;
INSERT INTO `drop_data` (`dropperid`, `itemid`, `minimum_quantity`, `maximum_quantity`, `questid`, `chance`) VALUES 

errors.txt is empty.

**Comment by ronancpl** [comment]
This issue happens because recently BBB Hidden-Street started adopting the certificate-protocoled HTTPS instead of HTTP on their domain. While changing "http" to "https" on the dropspider source would solve the URLs' location issue, there's still need to cover support for Certificates and SSL.

The dropspider issue should be archived, as it goes beyond the scope of this repo. The results that that program generated (roughly from 3 years ago) when it was last ran by myself can still be retrieved on the "db_drops.sql". The scope for that is between the first "INSERT INTO" statement and the comment line filled with a horizontal line, above "reinsert Kerning Square loot".

**Comment by ronancpl** [comment]
This article can help you achieve the dropspider support for HTTPS:

https://www.mkyong.com/java/java-https-client-httpsurlconnection-example/
