### ISSUE TITLE
Autoban issues: ultra three snail, and Slash Blast

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#220]
problem#1: autoban system banned some users using three snail, had to unban players and turn off **ultra** on the skill.

now ... problem#2 is about slash blast, autoban dc's out the player due to the skill using 9mp (low level skill) when autoban says it "should be" 14, but its 14-16 ish when the skill is MAXED (?) not sure if the player is MPCON hacking or not!

skill id: 10001005, player mp: 9; mp needed: 14
maybe autoban triggered by player's lag? if its lag, which would be a wise way to _solve_ this?
`if (player.getMp() < attackEffect.getMpCon()) {
                AutobanFactory.MPCON.addPoint(player.getAutobanManager(), "Skill: " + attack.skill + "; Player MP: " + player.getMp() + "; MP Needed: " + attackEffect.getMpCon());
                }`

**Comment by ronancpl** [comment]
The autoban is not being supported on this repository, so I'm closing this.

It could happen because of lag indeed, since the server may be triggering multiple handler calls where the current MP has lower value than the mpCon expects. A way to solve it is to either avoid using autoban for Mp consumption altogether or locking up the entire character MP handling system.
