### ISSUE TITLE
A way to truly tell if items exists.

### ISSUE THREAD

**Issue by UltimateMors** [ronancpl/HeavenMS#232]
This would be considered an enhancement. 

It would be great to make a way to actually truly check if an item exists in the files, this is good for my case, because I WZ edit a lot, however, I noticed the way it checks if a item exists, (In the !item method), is that it checks if the item has a name. 

The issue with doing this is that some items cannot be spawned unless you remove this check, because certain items, even in the clean files, do not have names. But, it  is a nightmare for me, because I cannot import names from multiple languages, and due to this, thousands of items I have do not have names.

I noticed in MapleItemInformationProvider has something called "isCash" but this is painfully broken and does not work. Everytime I tried using it, it just throws errors to hell in the console. Which, sort of fixed the problem in reality, but it's sort of annoying how it spams the console due to a nullpointerexeception, aka, the item does not exist. 

This is what I used in order to `if (ii.getEquipmentSlot(itemId) == null && ii.isCash(itemId) &&
ii.isCash(itemId)) {
					player.yellowMessage("Item id '" + sub[1] + "' does not exist.");
					break;
				}` check if a item exists or not, but it throws a null pointer in error, which is kind of annoying. Thanks for looking into this if you do, and thanks for the great source.

**Comment by resinate** [comment]
what intent do u have ur looking for, cuz i did add in a null check on dropped items

**Comment by UltimateMors** [comment]
I always liked the way it was checked in Lithium. By the actual item existing, and not by name. When a item does not have a name, you can't create it.

**Comment by ronancpl** [comment]
Truth be told, all items are expected to have name and description, no exceptions.

That's done for data logic security, it doesn't necessarily means that if some items doesn't have name the server will don't care anyway.

One can go ahead one day and create a new method requesting names for all itemids, for instance. Request all itemids: that's something preferrable to be fetched by reading the "String.wz" rather than "Item.wz" (speaking of read-performance), coupled with the logic that "all items have names and descriptions". It would be a hindrance to know there are some items with no string data that were not added there due to this.

Indeed, there were some items that had neither names nor descriptions before, but that's already solved on HeavenMS's side. Therefore I shouldn't be looking for a solution for this, and will close the issue.

**Comment by ronancpl** [comment]
Also, there's a tool devised to detect items with no name on XMLs. The name of the tool would be "MapleInvalidItemWithNoNameFetcher", you should use it to check all items with no string info on your side and add them manually, since having no string info is highly unadvised.
