### ISSUE TITLE
No sound, no mob hp, no mob name, no yellow message

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#245]
A player reports an odd issue today that i can't reproduce:

- he said he can't hear when he drops items
- can't see mobs hp bar
- can't see mobs names
- quest objectives yellow message won't appear in the top of screen

**Comment by ronancpl** [comment]
It's very likely a deadlock occurred at this rate. Quest/mob HPbar updates are passed to the player through packets, even then that player didn't receive the info.

I myself have experienced once not seeing mobs hp bar & name, would have judged that'd happen due to a mechanism on the localhost with the character being extremely low-level compared with the mob, but that doesn't seem to be the case.

**Comment by Arufonsu** [comment]
closed: not a server issue but a client issue
