### ISSUE TITLE
Cash shop codes / World maps /  local host descriptsions

### ISSUE THREAD

**Issue by seth1** [ronancpl/HeavenMS#258]
Presently if one enters a cash shop code nothing happens and one is unable to click code again.
This may seem like a useless feature but in the interest of being complete I think it should be added (or at least noted missing). Perhaps as a default dictionary in the back end it could be used to "recognize" itcg codes and throw out an item (P/C0# codes as seen here http://itcg.maplestorygameguide.com/codes.shtml).

As for world maps your art is impressive, but I'm not sure why you didn't use the pre-big bang map for Mushroom shrine available in SEA (see here: https://sea.hidden-street.net/map/zipangu). I'm also a little confused at why shrink Amoria down and threw it in with Victoria Island? And why is it when you hover over map items the scrolls change, clouds appear, and generally just change? That couldn't have been the original functionality.

The section on localhosts I find a little confusing. The first link presumably has all the fixes in the change log. "Fraysa's" I think should add the changes listed in this post http://forum.ragezone.com/f921/windows-10-v83-localhost-1121377/ so people know what it means. As for the other two that are beside two features, are those links 'clean' localhosts with only those features, or what are they? I think it should be described just for clarity's sake.

Thanks again for all your work!

**Comment by ronancpl** [comment]
I've read your remarks now, thanks for the feedback.

Indeed, it seems that currently the cash shop actions freeze after attempting to send a code, this issue will be dealt with. Also, I'll look into provide more information for the localhosts section.

Regarding world maps:

For the v83 Mushroom Shrine area, using the original artwork of that world map as template seemed the most viable action, since there were several aspects of the original artwork that did fit with the v83 Zipangu area surroundings.
Shrinking Amoria down was merely a matter of technical limitations, since it seems the localhost itself only recognizes very specific world map nodes for the "open worldmap" action. Since that happens, one world map room was needed for the World Tour region.
Finally, those other remarked worldmap issues were already present before, at least from the WZ base being used, and so they should remain as such. Treating them goes beyond my ability, thanks for understanding.
