### ISSUE TITLE
Another issue with LoginPasswordHandler

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#280]
![imagen](https://user-images.githubusercontent.com/17498701/48846145-18f1e100-ed7d-11e8-8dfd-13771f54cdaa.png)

**Comment by ronancpl** [comment]
After checking code, found out that to reach this rare scenario (with accountid 0 - probably defaulted), the system would need to have gone through confirming said accountid present on the DB (MapleClient.login) and after reaching function "MapleClient.finishLogin", not have said accountid on DB.

Due to the roundabout nature of this issue, I'm closing this now. Please report in should the issue persist.
