### ISSUE TITLE
Pirate quest to get Hypnotize can not be completed

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#283]
Two problems with the "Mission Free The Monsters" quest:

- The pink and blue mu lung snakes in the Parkour are supposed to warp you to stage 1 if you touch them (not a major issue)

- After completing the party quest where you have to protect Delli from the monsters, you exit through the portal and talk to the NPC. The NPC thanks you for saving her and warps you back to the training room. However, the "Mission Free The Monsters" quest does not get completed. pi.setQuestProgress(6410, 0, 1) does get called when you exit the portal, but for some reason this does not actually complete the quest. Is the progressid incorrect? (idk how it works)

**Comment by ronancpl** [comment]
![image](https://user-images.githubusercontent.com/9257761/49678587-7d46bd00-fa6c-11e8-8179-f4a349518c70.png)

It strikes to me the quest is being fulfilled properly, handing the skill properly. Did you make it to the portal at the top-right corner of the party quest map, so that you're transported to the depicted map?

About the Parkour map, noted! Will work on it soon.

**Comment by MedicOP** [comment]
Yes, I go through the portal and get teleported to the map, but for some reason the quest does not get cleared. There are no errors in the console either. The questprogress SQL table also shows the progress being added, but even after relogging it still does not show up correctly.

**Comment by ronancpl** [comment]
Implemented mob banish by touch. And questline should be completable using the most recent wz build. Please redownload contents to confirm this matter (please re-open this issue if the problem persists).
