### ISSUE TITLE
Magic damage super low

### ISSUE THREAD

**Issue by rafaelalmeidatk** [ronancpl/HeavenMS#288]
Seems like all the magic damages are being super low, the only exception is the Heal skill.

Magic Skill (Holy Arrow) damage:
![Magic Skill](https://cdn.discordapp.com/attachments/526182236580741131/527250662656835619/unknown.png)

Heal damage:
![Heal damage](https://cdn.discordapp.com/attachments/526182236580741131/527250749084794880/unknown.png)

Basic attack (no magic) damage: 
![Basic attack](https://cdn.discordapp.com/attachments/526182236580741131/527250908447244298/unknown.png)

I tried to debug the issue but seems like the low damage is being sent from somewhere other than the server, but I have no idea where it is coming from. Is the damage being calculated on the client-side?

**Comment by ronancpl** [comment]
You're right, the damage is being calculated and sent from the client-side.

However, differently from most mage skills, Heal also uses other stats in the calculation rather than only raw MATK, thus it will effectively do more damage in the upper limits.

By all effects, since MATK is a short-range value holder the max it possibly can have is over 32k, whereas WATK (integer-range) can go greatly over that since it takes other primary stats in the compound.

Closing this issue since it's client-related and should not interfere usual gameplay. Thanks for reporting.

**Comment by rafaelalmeidatk** [comment]
Thank you for the explanation, after some time digging on the dead links I managed to find a localhost that increases the cap.

Btw, great work on this project, it is AWESOME!
