### ISSUE TITLE
Scissors of karma can only be used once

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#302]
After you use Scissors of Karma on an item and trade it, trying to apply another scissor will give the message "Scissors of Karma was already used on this item."

However, in GMS, I'm fairly certain you can re-apply Scissors of Karma as many times as you want. Was this intended?

**Comment by MedicOP** [comment]
If this isn't intended, I can make a pull request to fix it. Let me know

**Comment by ronancpl** [comment]
It is not an intended feature, you can make a pull request for it.

**Comment by MedicOP** [comment]
https://github.com/ronancpl/HeavenMS/pull/307

**Comment by ronancpl** [comment]
@MedicOP 

Since you've been actively assisting a few times now on development, I'm proposing a HeavenMS staff roll entry for you (which gets displayed when typing @credits in-game).
```MedicOP - Adjunct Developer```

Two notes on this:
- You don't need to feel obligated to keep assisting to maintain this title, it's given as merit to your efforts.
- If you have a better suggestion for the title, let me know and we should be able to work it out.

**Comment by MedicOP** [comment]
Oh hey, sounds good lol, thanks!

I will keep on contributing :smile:

**Comment by ronancpl** [comment]
Cool.

I'd like to ask 2 topics if I may:
- Your nationality (that's just to get to know from where contributors are, you can answer it here or on the [survey](https://heavenms-survey.home.blog/))
- The one that has been authoring the PR's, @itsjh, would be somebody else in league with you?
