### ISSUE TITLE
MapleMap.startEvent(MapleCharacter chr) is never called

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#365]
`MapleMap.startEvent(MapleCharacter chr)` is never called from anywhere making the events not work.

Should it be called from a command?

**Comment by ronancpl** [comment]
Since GM Events generally are related to server-to-playerbase interaction rather than gaming issues, solving this one will be left open for contributors. If you like, feel free to fill in the missing points as you wish.

Note that the current classes implementation on that regard may be lacking or imprecise, their functionality should be checked thoroughly.

Yet answering your question, it could be done either through scripts or commands, depending on the application you want to do on it.
