### ISSUE TITLE
Nina's Request - Tasty Mushroom Candy Quest

### ISSUE THREAD

**Issue by ryantpayton** [ronancpl/HeavenMS#429]
Quest Id: 1034
Quest Name: Tasty Mushroom Candy

Issue:
If you drop the mushroom candy Nina gives you and talk to her she says she will give you 10 more. After talking to her nothing happens, only way to get more is forfeit the quest and accept it again.

Steps to reproduce:
 1. Accept quest **Tasty Mushroom Candy** after talking to Sen.
 2. Open your inventory and drop the **10 Mushroom Candy** Nina gave you.
 3. Talk to **Nina**

Note:
Not sure if this is by-design of MapleStory and if there is a fix or not. If there is no fix, just close this and ignore this issue.

**Comment by ronancpl** [comment]
There are many quests in MapleStory that seems to follow this pattern, on where quest items are given to one at its start and should be held until quest completion, from where it's taken off.

Possibly this quest is also like that. Since there is a workaround for this quest to be completable, this should not be an issue. Thanks for reporting!
