### ISSUE TITLE
PlayerNPC

### ISSUE THREAD

**Issue by amiga10** [ronancpl/HeavenMS#464]
When i summon player npc with : !playernpc myname game crashes,
when i relog to the same map the game keeps crash.

**Comment by ronancpl** [comment]
Have you tried using the recommended WZ's on readme's download section? The issue should not persist that way.

https://github.com/ronancpl/HeavenMS#download-items

If you are using other Wz's, you may want to check out the `scriptid` that is being deployed, maybe the client-side has no registry about it, hence crashing the game locally.

Alternatively, if you may, please show the `scriptid` giving out the issue so that this case can be further analyzed.

**Comment by amiga10** [comment]
![image](https://user-images.githubusercontent.com/34136990/57324747-27586d00-7111-11e9-9e9e-af02f4f69d18.png)
Which one do i have to download?

**Comment by amiga10** [comment]
Ty, works
