### ISSUE TITLE
Speed Infusion buff is causing "Reached the end of file" while changing map.

### ISSUE THREAD

**Issue by xinyifly** [ronancpl/HeavenMS#478]
I think commit `Party Search + Conditional Buffs` bb80441 caused this issue.

**Comment by ronancpl** [comment]
Yeah, though that issue is not probably related to a flaw in buff update code.

Somehow, trying to update the buff "Speed Infusion" (only case I got it happening) whilst still transitioning through maps will render an error 38 (even with larger packet lengths, which may suggest a need for different packet structure when handling it in that scenario).

Anyway, a practical solution already known for that would be to not update that skill when performing the update (which is done by the conditional buffs system).

**Comment by ronancpl** [comment]
Commit a39a210c1f6993a8747ba43f160c5b8dbfe761f2 cleared this case. Thanks for reporting!
