### ISSUE TITLE
Hello to the developer 

### ISSUE THREAD

**Issue by beloved26** [ronancpl/HeavenMS#482]
How to Set Language as Chinese

**Comment by beloved26** [comment]
Modify the localhost file to enter Chinese in the game. But I want to know how to make the game interface menu appear as Chinese.

**Comment by ronancpl** [comment]
Hi @beloved26.

Unfortunately, this server development only supports ASCII encoding-set and, for extent regarding gaming experience and coding, English language.

Although bug fixes take place in order to improve gameplay, generally tweaks on the client-side of things are not within the scope of this development.

Apologies for the inconvenience. Have a good search.
