### ISSUE TITLE
server doesnt work

### ISSUE THREAD

**Issue by resinate** [ronancpl/HeavenMS#486]
https://cdn.discordapp.com/attachments/538350131653771264/599524660010418176/unknown.png

dunno whats wrong here

**Comment by ronancpl** [comment]
The issue has already been cleared, but replicating the solution here.

The image, that could not be rendered properly outside the Discord app, is as follow.

![image](https://user-images.githubusercontent.com/9257761/61184657-b6f52d00-a626-11e9-9bb5-1079bae3b27e.png)

This issue happens due to the Mina JAR not being located properly by the JVM classpath finder.

The "launch.bat" tries to locate JAR's within the "dist" folder (`set CLASSPATH=.;dist\*`), double-check if you got the 5 core JAR's in a subfolder around there.
