### ISSUE TITLE
GM EVENT

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#516]
![image](https://user-images.githubusercontent.com/26664343/63839986-d7006600-c9b2-11e9-8b98-745e630891ec.png)
I want to know how these events work correctly.
I found the startup method to be very cumbersome.

**Comment by ronancpl** [comment]
Well, none of those events were reliably tested, so cannot vouch for how well they will fare.

So far checking MapleCoconut.java, for instance, there are a few things to be noted:

- `getMapleScore() > getStoryScore()`: there are two teams from where the players are assigned. So far, team assigned for GM event seems to happen during JoinEventCommand, here `player.setTeam(event.getLimit() % 2);`

, in several scenarios, MapleCoconut implements `warpOut()`, which by the looks of it may be the ending sequence of the event.

And finally, the event seems to start at call `MapleMap.startEvent`, which had been set to start at StartMapEventCommand.

Note that there will probably have a need for a few tweaks in order of those events to run properly. Since the issue in question is more that of a feature, sorry for the inconvenience, but this should be closed...
