### ISSUE TITLE
Quest reset help needed!

### ISSUE THREAD

**Issue by symphofear** [ronancpl/HeavenMS#517]
Hi, I'm working on a rebirth version for this server and currently need some help on resetting or deleting existing quests attached to the character upon rebirth. Currently Cygnus job unable to take new job advancement due to the previous beginner quest completed. 

Can anyone help/guide me on the codes? There seems to be no way to delete/modify the quest when character is logged in.

**Comment by ronancpl** [comment]
`currently need some help on resetting or deleting existing quests attached to the character upon rebirth`

This may no longer be an issue, but so to answer this...

That can be achieved by *unprogressing* all player quests. To do it, `MapleQuest::reset(MapleCharacter chr)` covers the situation, as it flags a given `MapleQuest.getInstance(int questid)` as NOT_STARTED.

Therefore, you should iterate over all quests the player currently holds. You can do it by traversing MapleCharacter's `quests.keySet()`, which should return all quests the player has progressed.

Perhaps after doing that you may want to use `saveCharToDB`, so that this update immediately persists in the database.
