### ISSUE TITLE
Disconnect with error code 5 whenever saving char to DB

### ISSUE THREAD

**Issue by kugatsuno** [ronancpl/HeavenMS#522]
When saving char to DB appears in the console, players would immediately disconnect with an error code 5

In additional, whenever an I/L Mage casts any 4th job skills, it calls the saveChartoDB method and disconnects with the same error code 5 as well.

Can't figure out why for the life of me, any help is appreciated.

**Comment by ronancpl** [comment]
Reportedly, error 5 started appearing after a recent change in MagicDamageHandler, on which usage of non-magic damage packet led to disconnections to other players, upon using skills such as Fire Arrow. Said change took place in order to address another issue, but it seems to have backfired.

Reverting the changes, that is, making all skills on that handler use `packet = MaplePacketCreator.magicAttack(chr, attack.skill, attack.skilllevel, attack.stance, attack.numAttackedAndDamage, attack.allDamage, attack.charge, attack.speed, attack.direction, attack.display);` should clear this case.

**Comment by ronancpl** [comment]
This should have been cleared now, after reverting the changes on `MagicDamageHandler`... Please reopen should the issue persists.
