### ISSUE TITLE
Temple of Time

### ISSUE THREAD

**Issue by alexprince7** [ronancpl/HeavenMS#524]
I can't get passed a certain point in the temple of time. I did all the quests until the whale ate my memories. So I talked to the memory keeper, followed along the quest and went to my 1st job advancement instructor, then back to the memory keeper and now he doesn't say anything. Although he has the brown book above his head signifying the quest is just about complete. So I now can't get go further into certain rooms in the temple of time

**Comment by ronancpl** [comment]
Greetings.

After the recent update 7ee947b4041852b33832d856b464abfe0ceafb8e a few quests have had their progress checking reviewed. A few of them used to have contingency script quests in order to supply for the lack of requirement matching.

Currently, following the memory keeper quest should have this flow:

![image](https://user-images.githubusercontent.com/9257761/66450027-6d518e00-ea2d-11e9-9254-c751a58a3756.png)

Ending with the player being able to talk to the NPC and completing it:

![image](https://user-images.githubusercontent.com/9257761/66450076-94a85b00-ea2d-11e9-8679-af7fc85e5b8c.png)

Two possible solutions for the scenario you have found would be to either:
- redownload the files present on "current_wz" (recommended);
- add the [quest script file](https://github.com/ronancpl/HeavenMS/blob/e169971384fa59e5bb2eb4cf279852b674269d4a/scripts/quest/3507.js) back in "scripts/quest" folder.

**Comment by alexprince7** [comment]
![memory](https://user-images.githubusercontent.com/56327238/66460965-d8e72b80-ea2c-11e9-97e9-b9f0f263e0f8.png)

Hey Ronan thanks for the quick reply. So I re-downloaded the wz files and I also replaced the entire scripts folder. For some reason the quest no longer recorded that I talked to the 1st job npc, and now when I go to talk to her she doesn't say anything regarding the quest.

**Comment by alexprince7** [comment]
Okay I figured it out. I had to go into mysql and clear the quest "In Search For Lost Memory" 3525 and set it to incomplete and status 0. And then it worked! :D
