### ISSUE TITLE
Quest "How to Shop Awav the Evil(Pre-completion enabled)" can't complete 

### ISSUE THREAD

**Issue by kvmba** [ronancpl/HeavenMS#526]
![QQ截图20191010201548](https://user-images.githubusercontent.com/2517326/66567996-fafebc00-eb9a-11e9-8c4e-907e8fadbc8f.png)

Can't complete , NPC say nothing and Server Console not display anything 。
thanks.  :)

**Comment by xinyifly** [comment]
Have you talked to all the 6 tombs? [How to Shoo Away the Evil](https://bbb.hidden-street.net/quest/victoria-island/how-to-shoo-away-the-evil)

**Comment by kvmba** [comment]
![QQ截图20191010202349](https://user-images.githubusercontent.com/2517326/66568374-e3740300-eb9b-11e9-9894-a72648805181.png)
yes.

**Comment by ronancpl** [comment]
Oh, that's the problem.

![image](https://user-images.githubusercontent.com/9257761/66623685-33b28b80-ebc3-11e9-909d-1b85b376eba9.png)

This quest had expected a "infoNumber" having the same value as the questid. To be honest, back when I passed through this quest, the sketched `setQuestProgress` defaulted infoNumber as the same value as the questid's. However, some time later this approach had been changed this default:

![image](https://user-images.githubusercontent.com/9257761/66623767-973cb900-ebc3-11e9-8f61-ffc20e69ec7c.png)

Since quest's expected infoNumber and progress' infoNumber mismatch, the quest couldn't yet be completed...

**Comment by ronancpl** [comment]
The issue showed up due to the value returned on `MapleQuestStatus::getProgressData()` mismatching with the required by the client files to end the quest.

![image](https://user-images.githubusercontent.com/9257761/66876309-bc487780-ef87-11e9-9d04-74a42ce1d3f4.png)

By performing that, the string returned by acquired progress at 2236, when talking to the quest rocks, should match the expected string ("111111").
