### ISSUE TITLE
Port Forwarding IoSessions

### ISSUE THREAD

**Issue by cihadpalta** [ronancpl/HeavenMS#542]
Hello everyone,

First of all I would like to thank all the contributors for this source.
So I've just put up the server to play with my students, while port forwarding the port **7575-7577 (3 channels)**, **8484** and **_80_** (for a website in the future) I couldn't connect to the server myself and also my student couldn't. 

After looking over everything a couple of times, I noticed in the launch.bat the ports after the **IoSession** with IP address keeps changing ranging from **34k to 44k**. Is there any way to assign these ports somewhere? Because now I've port forwarded **8484-65535** just to be sure every session gets accepted. I would like to make this range smaller for security reasons etc.

Hope someone can help me with this.

Kind Regards,

Cihad

**Comment by ronancpl** [comment]
Greetings @cihadpalta,

Yes, there is a way to move the range of ports to be used for the IoSession connections. However, the solution to be presented acts more specifically at environment-level rather than per program-basis, please keep that in mind.

Essentially, on the machines requesting connections to the server, with "Administrator privileges" at hand (and assuming those machines runs with OS Windows), handle the following:
* Open the **command prompt**. For that: click Start menu, search "cmd", then press Enter;
* Type "`netsh int ipv4 set dynamicport tcp start=<base_port_id> num=<pool_limit>`", pool_limit: 255+;
* Open the game.

Assuming all procedures went fine, IoSessions should get pinged within the given range. This should be an action to be implemented on each machine running the game.

More info on [https://support.microsoft.com/en-us/help/929851/the-default-dynamic-port-range-for-tcp-ip-has-changed-in-windows-vista](https://support.microsoft.com/en-us/help/929851/the-default-dynamic-port-range-for-tcp-ip-has-changed-in-windows-vista)

Good entertainment for your class.

Best regards,
Ronan

**Comment by ronancpl** [comment]
By the way, to make sure to return those values back to default, make sure to run `netsh int ipv4 show dynamicport tcp` **before** applying the dynamic port changes above.

**Comment by ronancpl** [comment]
Finally, make sure to open the **command prompt as Administrator**: https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/

**Comment by xinyifly** [comment]
Somehow I suspect there might be nothing wrong with ports if you blame something like this:

```text
IoSession with /1.2.3.4:34445 opened on 11-13-2019 03:58
```

If my guess correct, then I suggest to check `configuration.ini` to ensure the part

```ini
HOST=127.0.0.1
```

while `127.0.0.1` should be your router's ip. (From "Port Forwarding", I guess you are using a router)

**Comment by cihadpalta** [comment]
> Greetings @cihadpalta,
> 
> Yes, there is a way to move the range of ports to be used for the IoSession connections. However, the solution to be presented acts more specifically at environment-level rather than per program-basis, please keep that in mind.
> 
> Essentially, on the machines requesting connections to the server, with "Administrator privileges" at hand (and assuming those machines runs with OS Windows), handle the following:
> 
> * Open the **command prompt**. For that: click Start menu, search "cmd", then press Enter;
> * Type "`netsh int ipv4 set dynamicport tcp start=<base_port_id> num=<pool_limit>`", pool_limit: 255+;
> * Open the game.
> 
> Assuming all procedures went fine, IoSessions should get pinged within the given range. This should be an action to be implemented on each machine running the game.
> 
> More info on https://support.microsoft.com/en-us/help/929851/the-default-dynamic-port-range-for-tcp-ip-has-changed-in-windows-vista
> 
> Good entertainment for your class.
> 
> Best regards,
> Ronan

Dear Ronan,

Thanks for your response!
So actually it is something that can be fixed only from the client side? Is there no other way to fix it from the server side so the clients don't have to apply any changes on their system?

Kind Regards,

Cihad

**Comment by cihadpalta** [comment]
> Somehow I suspect there might be nothing wrong with ports if you blame something like this:
> 
> ```
> IoSession with /1.2.3.4:34445 opened on 11-13-2019 03:58
> ```
> 
> If my guess correct, then I suggest to check `configuration.ini` to ensure the part
> 
> ```ini
> HOST=127.0.0.1
> ```
> 
> while `127.0.0.1` should be your router's ip. (From "Port Forwarding", I guess you are using a router)

Thanks for your response but this has nothing to do with my question.

**Comment by cihadpalta** [comment]
Hey guys,

Somehow it works without any changes now. After rebooting and changing the port forward of 8484-65535 tot 8484-8484 it still works. The port of IoSessions are now in the range of 2k somehow. I have no idea what happened, but it works, for now..

Thanks for the help.
