### ISSUE TITLE
Error trying to Launch the server

### ISSUE THREAD

**Issue by JanexLane** [ronancpl/HeavenMS#552]
" **Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Press any key to continue . . .** "

this error shows up when I try to start up the server! I'm not sure what it means or how to really fix it. I know it says there's not enough space but when I have my computer cleaned out and open so I'm not sure what the problem is.
Please help!

**Comment by ronancpl** [comment]
Hi @JanexLane,

To clear out this error, you will need to place a value to be used when allocating memory for the JVM.

Look into the `launch.bat` file and edit the numeric value within `-Xmx2048m` for something less, in order to avoid hardware heap space limits, as 2048m implies an attempt to allocate 2048MB from the machine's available space in one go.

**Comment by JanexLane** [comment]
thanks a bunch! that fixed it

**Comment by ronancpl** [comment]
No problem, glad being of help.
